# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GofsenCli < Formula
  desc "Gofsen CLI - Minimalist web API framework scaffolding for Go"
  homepage "https://github.com/Bakemono-san/gofsen"
  version "1.2.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bakemono-san/gofsen/releases/download/v1.2.6/gofsen_1.2.6_darwin_amd64.tar.gz"
      sha256 "c1b2a86e2eca09de13d2209cca5db44ec12f0b61dd0b981923fdd889108c0bcd"

      def install
        bin.install "gofsen-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bakemono-san/gofsen/releases/download/v1.2.6/gofsen_1.2.6_darwin_arm64.tar.gz"
      sha256 "a2dc7b8222ec74712fa14c03e2bffb5ec4130a9088d33c3f0af85edee4d7a730"

      def install
        bin.install "gofsen-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bakemono-san/gofsen/releases/download/v1.2.6/gofsen_1.2.6_linux_amd64.tar.gz"
      sha256 "c852c277b155fc9860f14159c1658a615544aafca3af4b813b57f521e846d927"
      def install
        bin.install "gofsen-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bakemono-san/gofsen/releases/download/v1.2.6/gofsen_1.2.6_linux_arm64.tar.gz"
      sha256 "86841b08779faac62fb4374e3892c56b605c32dc991c9ed2a628de1decd8ad14"
      def install
        bin.install "gofsen-cli"
      end
    end
  end

  test do
    system "#{bin}/gofsen-cli", "--version"
  end
end
