# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GofsenCli < Formula
  desc "Gofsen CLI - Minimalist web API framework scaffolding for Go"
  homepage "https://github.com/Bakemono-san/gofsen"
  version "1.2.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bakemono-san/gofsen/releases/download/v1.2.8/gofsen_1.2.8_darwin_amd64.tar.gz"
      sha256 "6e1b206a3b530fede4a9f7ed2e1b578b41012ba0d03b57b39eacf5221e776db1"

      def install
        bin.install "gofsen-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bakemono-san/gofsen/releases/download/v1.2.8/gofsen_1.2.8_darwin_arm64.tar.gz"
      sha256 "daeb072eac3eec8fa071be5777093ce18fe789353e41715b027e432c4f79ad15"

      def install
        bin.install "gofsen-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bakemono-san/gofsen/releases/download/v1.2.8/gofsen_1.2.8_linux_amd64.tar.gz"
      sha256 "aee7a1e76f9ad902e34e8ad469f726f6856d9847d9ae1958cf78fb44a02659ab"
      def install
        bin.install "gofsen-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bakemono-san/gofsen/releases/download/v1.2.8/gofsen_1.2.8_linux_arm64.tar.gz"
      sha256 "7995039bb57942967ff0e0c084065f12ca9922a9154d5401921e7591df0db6bd"
      def install
        bin.install "gofsen-cli"
      end
    end
  end

  test do
    system "#{bin}/gofsen-cli", "--version"
  end
end
